# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-05 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='twitter',
            new_name='tweet',
        ),
    ]
